x=int(input("Please enter 1st number"))
y=int(input("Please enter 2nd number"))
z=int(input("Please enter 3rd number"))
print("The max of three values is :")
print(max(x,y,z))
input("Please press enter to exit")
